server:
  port: 8081


eureka:
  instance:
    hostname: localhost
  #    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/